# find StormLib
# STORMLIB_LIBRARIES - where libraries located
# STORMLIB_INCLUDE_DIRS - where include files located
# STORMLIB_FOUND - true if we found include files and library

#cache 
IF( STORMLIB_INCLUDE_DIRS AND STORMLIB_LIBRARIES )
	SET( STORMLIB__FIND_QUIETLY TRUE )
ENDIF( STORMLIB_INCLUDE_DIRS AND STORMLIB_LIBRARIES )

FIND_PATH( STORMLIB_INCLUDE_DIR StormLib.h PATH_SUFFIXES stormlib StormLib )
FIND_LIBRARY( STORMLIB_LIBRARY NAMES storm )

SET( STORMLIB_INCLUDE_DIRS ${STORMLIB_INCLUDE_DIR} )
SET( STORMLIB_LIBRARIES ${STORMLIB_LIBRARY} )

INCLUDE( FindPackageHandleStandardArgs )
FIND_PACKAGE_HANDLE_STANDARD_ARGS( StormLib DEFAULT_MSG STORMLIB_LIBRARIES STORMLIB_INCLUDE_DIRS  )


