#[[.rst
FindGMP
---------
GMP_FOUND - system has gmp
GMP_INCLUDE_DIRS - gmp include directory
GMP_LIBRARIES - gmp library
#]]

if (GMP_INCLUDE_DIR AND GMP_LIBRARY )
	set(GMP_FIND_QUIETLY TRUE)
endif(GMP_INCLUDE_DIR AND GMP_LIBRARY)

find_path(GMP_INCLUDE_DIR NAMES gmp.h PATHS ${CMAKE_SOURCE_DIR}/depends/include)
find_library(GMP_LIBRARY NAMES gmp libgmp PATHS ${CMAKE_SOURCE_DIR}/depends/lib )

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GMP DEFAULT_MSG GMP_LIBRARY GMP_INCLUDE_DIR )

SET( GMP_LIBRARIES ${GMP_LIBRARY} )
SET( GMP_INCLUDE_DIRS ${GMP_INCLUDE_DIR} )
