# find GMP
# GMP_FOUND - true if we found gmp library and include files
# GMP_LIBRARIES - where gmp library located
# GMP_INCLUDE_DIRS - where gmp iclude files located

IF (GMP_INCLUDE_DIRS AND GMP_LIBRARIES )
	set(GMP_FIND_QUIETLY TRUE)
ENDIF(GMP_INCLUDE_DIRS AND GMP_LIBRARIES)

FIND_PATH(GMP_INCLUDE_DIR NAMES gmp.h )
FIND_LIBRARY(GMP_LIBRARY NAMES gmp libgmp )

SET( GMP_LIBRARIES ${GMP_LIBRARY} )
SET( GMP_INCLUDE_DIRS ${GMP_INCLUDE_DIR} )

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GMP DEFAULT_MSG GMP_LIBRARIES GMP_INCLUDE_DIRS )
